In [1]:
import pandas as pd

data = pd.read_csv('raw_data.csv')
data.head()

,file_path,extracted_text
0,../XQUANG\20240226\20240226013\20240226013_202...,TTYT-HUYEN DUC TRONG Series 1 20240226013 Imag...
1,../XQUANG\20240226\20240226013\20240226013_202...,TTYT-HUYEN DUC TRONG Series 1 20240226013 Imag...
2,../XQUANG\20240226\20240226013\20240226013_202...,TTYT-HUYEN DUC TRONG Series 1 20240226013 Imag...
3,../XQUANG\20240226\20240226014\20240226014_202...,TTYT-HUYEN DUC TRONG Series 1 20240226014 Imag...
4,../XQUANG\20240226\20240226015\20240226015_202...,TTYT-HUYEN DUC TRONG Series 1 20240226015 Imag...

In [2]:
# Duplicate extracted_text column
data['name'] = data['extracted_text']

In [21]:
# Remove "TTYT-HUYEN DUC TRONG" in name column
data['name'] = data['name'].str.replace('TTYT-HUYEN DUC TRONG', '', regex=False)
data['name'] = data['name'].str.replace('UTYTHUYEN DUC TRONG', '', regex=False)
data['name'] = data['name'].str.replace('TTYTHUYE N DUC TRONG ', '', regex=False)
data['name'] = data['name'].str.replace('ITYTHUYEN DUC', '', regex=False)
data['name'] = data['name'].str.replace('TTYTHUYENDUC TRONG', '', regex=False)
data['name'] = data['name'].str.replace('YTHUYENDUC TRONG ', '', regex=False)
data['name'] = data['name'].str.replace('TTYTHOYEN DUC TRONG', '', regex=False)
data['name'] = data['name'].str.replace('TTYTEHUYENDUC TRONG', '', regex=False)

# Save a draft of cleaned data
data.to_csv('cleaned_data_draft.csv', index=False)

In [4]:
# Remove all numbers from name column
data['name'] = data['name'].str.replace(r'\d+', '', regex=True)
data.to_csv('cleaned_data_draft.csv', index=False)

In [5]:
# Remove "extracted_text" column
data = data.drop(columns=['extracted_text'])
data.to_csv('cleaned_data_draft.csv', index=False)

In [6]:
# Remove "Pixel for Pixel" from name column
data['name'] = data['name'].str.replace('Pixel for Pixel', '', regex=False)
data.to_csv('cleaned_data_draft.csv', index=False)

In [7]:
# Remove special characters from name column
data['name'] = data['name'].str.replace(r'[^\w\s]', '', regex=True)
data.to_csv('cleaned_data_draft.csv', index=False)

In [22]:
# Remove " Series   Image  " from name column
data['name'] = data['name'].str.replace(' Series   Image  ', '', regex=False)
data['name'] = data['name'].str.replace(' Series    Image  ', '', regex=False)
data['name'] = data['name'].str.replace(' Series  Image ', '', regex=False)
data['name'] = data['name'].str.replace(' Series  mage ', '', regex=False)
data['name'] = data['name'].str.replace(' Series I  Image ', '', regex=False)
data['name'] = data['name'].str.replace('Series  Image  ', '', regex=False)
data['name'] = data['name'].str.replace('Series    mage  ', '', regex=False)
data.to_csv('cleaned_data_draft.csv', index=False)

In [20]:
# Remove whitespace from start and end of name column
data['name'] = data['name'].str.strip()
data.to_csv('cleaned_data_draft.csv', index=False)

---

In [7]:
draft = pd.read_csv('cleaned_data_draft.csv')
draft.head()

,file_path,name
0,../XQUANG\20240226\20240226013\20240226013_202...,MA THI NGUYET CSPINE AP
1,../XQUANG\20240226\20240226013\20240226013_202...,MA THI NGUYET CSPINE AP
2,../XQUANG\20240226\20240226013\20240226013_202...,MA THI NGUYET CSPINE AP
3,../XQUANG\20240226\20240226014\20240226014_202...,NGUYEN DANG TUAN CHEST PA
4,../XQUANG\20240226\20240226015\20240226015_202...,NGUYEN QUE SKULLI AP

In [5]:
remove_text = [
    'Unit cm', 
    'Unit ci', 
    'Unit CM', 
    'Unit CI',
    'Unit Cm', 
    'Unit Om',
    'Mag X Admin W  L', 
    'Pixelf forPixel', 
    'Mag X Admin Wa  L', 
    'Pixel forPixel Mag X Admin W',
    'Mag X Admin W L',
    'PixeltonPirel Mag  Admin W L',
    'Pixelfor Pixel Mage  Admin W  L',
    'Mag X Admin W',
    ''
]
for text in remove_text:
    draft['name'] = draft['name'].str.replace(text, '', regex=False)
draft['name'] = draft['name'].str.strip()
draft.to_csv('cleaned_data_draft.csv', index=False)